### ISSUE TITLE
Improve design for inactive stations in DetailsActivity

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#141]
Inactive stations are now marked with a text `Station inactive` on the Details page. 

Example in portrait mode:
![Screenshot_20191002-233050_Railway_station_photos](https://user-images.githubusercontent.com/5598124/66084179-4814d980-e56e-11e9-8e2f-34f7b76db92e.png)

Example in landscape mode:
![Screenshot_20191002-233040_Railway_station_photos](https://user-images.githubusercontent.com/5598124/66084185-4c40f700-e56e-11e9-8de7-db7b6b27402d.png)

It feels a bit like too much text, but I don't have a good idea here. Any suggestion on how to improve the design? 
- add `(inactive)` to the title
- add an icon which indicates inactivity
- use different colors
- ...

**Comment by pstorch** [comment]
An inactive indicator (maybe the same as here) would also be usefull on the MainActivity.

**Comment by kaiwinter** [comment]
Oh, the space between the coordinates and the "inactive" line wasn't intentional. There should be the comment line I think. Seems as it is has a Visibility of INVISIBLE instead of GONE.

But anyway I think "inactive" should be added to the title. In landscape I see no problems with this. In portrait mode the text may be too long (does it break to the next line?) 
An icon have to be explained somewhere. That is somehow missing at the moment. So adding the station icon in front of the station name seems also a good idea. On a tap on the icon an explanation can be shown.

Another idea would be to just hide all overlays in landscape and show the station title in the header instead of "Station details". Hm but there may be photos which are taken in portrait mode.

Are the coordinates useful at all? Or can they maybe removed from both orientations?

**Comment by pstorch** [comment]
> Oh, the space between the coordinates and the "inactive" line wasn't intentional. There should be the comment line I think. Seems as it is has a Visibility of INVISIBLE instead of GONE.

Right, that should be changed. I already felt that the comment is too much here. Maybe it is better to ask for a comment right before uploading in a dialog.

> But anyway I think "inactive" should be added to the title. In landscape I see no problems with this. In portrait mode the text may be too long (does it break to the next line?)

Yes, it can break to the next line, like this:

![Screenshot_20191003-094327_Railway_station_photos](https://user-images.githubusercontent.com/5598124/66114729-c35aa780-e5cf-11e9-95a3-dbc7cc77c819.png)

We already add the station id to the title in parenthesis, which adds to the line length. Adding "inactive" would make it even longer.

> An icon have to be explained somewhere. That is somehow missing at the moment. So adding the station icon in front of the station name seems also a good idea. On a tap on the icon an explanation can be shown.

I kind of like the idea, could open an info screen (see  idea below).

> Another idea would be to just hide all overlays in landscape and show the station title in the header instead of "Station details". Hm but there may be photos which are taken in portrait mode.

The photos should always be taken in landscape mode, that's the hint we show at the bottom. Putting the title in the actionbar is also an idea, but it would have to be truncated, right?

> Are the coordinates useful at all? Or can they maybe removed from both orientations?

Yes, this information is somewhat unnecessary. Maybe we could move the coordinates together with the station id into info popup dialog. Reachable via the marker icon. 

There is another problem: the title is hard to read. Maybe because I changed the TextView to an EditText, which is disabled most of the time.
